#!/bin/bash

cupstack_install_compiler() {
  if [ "$#" -ne 3 ]; then
    echo "Function requires:"
    echo "1. Install Prefix"
    echo "2. Temporary Directory"
    echo "3. Parallel Number of Jobs"
    return 1
  fi

  INSTALL_PREFIX=$1
  TEMPORARY_DIRECTORY=$2
  PARALLEL_JOBS=$3

  SOURCE_URL=https://developer.download.nvidia.com/hpc-sdk/21.2/nvhpc_2021_212_Linux_x86_64_cuda_11.2.tar.gz

  ARCHIVE_DIRECTORY=$TEMPORARY_DIRECTORY/archive
  BUILD_DIRECTORY=$TEMPORARY_DIRECTORY/build
  SOURCE_DIRECTORY=$TEMPORARY_DIRECTORY/src

  TOPLEVEL_SUBDIRECTORY="nvhpc_2021_212_Linux_x86_64_cuda_11.2"

  mkdir -p $TEMPORARY_DIRECTORY
  mkdir -p $BUILD_DIRECTORY
  mkdir -p $SOURCE_DIRECTORY
  mkdir -p $ARCHIVE_DIRECTORY

  wget --quiet $SOURCE_URL -O $ARCHIVE_DIRECTORY/source.tar.gz
  tar -xzpf $ARCHIVE_DIRECTORY/source.tar.gz -C $SOURCE_DIRECTORY

  pushd $SOURCE_DIRECTORY/$TOPLEVEL_SUBDIRECTORY
    export NVHPC_SILENT=true
    export NVHPC_INSTALL_DIR=$INSTALL_PREFIX
    export NVHPC_INSTALL_TYPE=local
    ./install
  popd

}
